feat: build web docker test

diff --git a/docker/Dockerfile.web b/docker/Dockerfile.web
--- a/docker/Dockerfile.web
+++ b/docker/Dockerfile.web
@@ -10,27 +10,37 @@ ENV HTTPS_PROXY=${HTTPS_PROXY}
 ENV npm_config_proxy=${HTTP_PROXY}
 ENV npm_config_https_proxy=${HTTPS_PROXY}
 
-# Verify proxy settings
-RUN echo "Checking proxy settings..." && \
-  echo "HTTP_PROXY: $HTTP_PROXY" && \
-  echo "HTTPS_PROXY: $HTTPS_PROXY"
+# Install build dependencies
+# RUN apk add --no-cache python3 make g++
 
-# Copy package.json first
-COPY frontend/web/package*.json ./
+# Copy package.json and script first
+COPY frontend/web/package.json ./package.json
+COPY frontend/web/prepare-web-package.js ./prepare-web-package.js
+COPY frontend/web/tsconfig.json ./tsconfig.json
 
-# Install dependencies with specific npm settings
-RUN npm install
+# Run script to prepare web package.json
+RUN node prepare-web-package.js && \
+  mv package.web.json package.json && \
+  rm prepare-web-package.js
 
-# Copy source code
+# Install dependencies
+RUN npm install --legacy-peer-deps
+
+# Copy source code (only web-related files)
 COPY frontend/web .
 
 # Build application
-RUN npm run build
+RUN npm run build:web
 
 # Production stage
 FROM nginx:alpine
 COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
-COPY --from=builder /app/app /usr/share/nginx/html
+
+RUN ls -la /app && \
+  echo "Listing /app/.next directory:" && \
+  ls -la /app/.next || echo "/.next directory not found" && \
+  COPY --from=builder /app/.next /usr/share/nginx/html
+
 ENV PORT=80
 EXPOSE ${PORT}
 CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
